name: Aggregate AI News

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 */3 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  aggregate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: go.sum
      
      - name: Install dependencies
        run: |
          go mod download
          go mod verify
      
      - name: Run aggregator
        run: |
          go run cmd/aggregator/main.go
        env:
          TZ: UTC
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet public/news-data.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'AI Report Bot'
          git config --global user.email 'bot@ai-report.com'
          git add public/news-data.json
          git add public/archive/
          git commit -m "Update AI news - $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
      
      - name: Trigger site rebuild
        if: steps.check_changes.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'main'
            })

  # Optional: Send notification on failure
  notify-failure:
    runs-on: ubuntu-latest
    needs: aggregate
    if: failure()
    steps:
      - name: Send failure notification
        run: |
          echo "News aggregation failed at $(date -u +'%Y-%m-%d %H:%M UTC')"
          # Add your notification logic here (e.g., send email, Slack message, etc.) 